# Generated by Django 5.1 on 2024-08-31 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_end', models.IntegerField(db_index=True)),
                ('fight_duration', models.IntegerField(db_index=True)),
                ('boss_name', models.CharField(db_index=True, max_length=64)),
                ('difficulty', models.CharField(db_index=True, max_length=10)),
                ('max_hp', models.BigIntegerField(null=True)),
                ('max_hp_bars', models.IntegerField(null=True)),
                ('npc_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncounterPreviewPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16)),
                ('character_id', models.BigIntegerField(null=True)),
                ('class_id', models.IntegerField(db_index=True)),
                ('subclass', models.CharField(db_index=True, max_length=20, null=True)),
                ('dps', models.IntegerField(db_index=True)),
                ('gear_score', models.FloatField(db_index=True)),
                ('is_dead', models.BooleanField(db_index=True)),
                ('party_num', models.IntegerField()),
                ('local_player', models.BooleanField(default=False)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='homepage.encounterpreview')),
            ],
        ),
    ]
