# Generated by Django 5.1 on 2024-09-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=10)),
                ('fight_end', models.IntegerField(db_index=True)),
                ('fight_duration', models.IntegerField(db_index=True)),
                ('boss_name', models.CharField(db_index=True, max_length=64)),
                ('difficulty', models.CharField(db_index=True, max_length=9)),
                ('max_hp', models.BigIntegerField(null=True)),
                ('npc_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncounterPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16)),
                ('character_id', models.BigIntegerField(null=True)),
                ('class_id', models.IntegerField(db_index=True)),
                ('subclass', models.CharField(db_index=True, max_length=26, null=True)),
                ('dps', models.IntegerField(db_index=True)),
                ('gear_score', models.FloatField(db_index=True)),
                ('is_dead', models.BooleanField(db_index=True)),
                ('death_timer', models.IntegerField(db_index=True)),
                ('death_count', models.IntegerField(db_index=True)),
                ('party_num', models.IntegerField()),
                ('display_name', models.BooleanField(default=False)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='encounter.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='EncounterPlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counters', models.IntegerField()),
                ('casts', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('crits', models.IntegerField()),
                ('dmg_total', models.BigIntegerField()),
                ('dmg_back_attacks', models.BigIntegerField()),
                ('dmg_front_attacks', models.BigIntegerField()),
                ('dmg_debuffed_supp_brand', models.BigIntegerField()),
                ('dmg_buffed_supp_ap', models.BigIntegerField()),
                ('dmg_buffed_supp_identity', models.BigIntegerField()),
                ('buffs', models.JSONField(default=dict)),
                ('debuffs', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_data', to='encounter.encounterplayers')),
            ],
        ),
    ]
