# Generated by Django 5.1 on 2024-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterplayers',
            name='subclass',
            field=models.CharField(db_index=True, max_length=26, null=True),
        ),
    ]
