# Generated by Django 5.1 on 2024-09-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('avatar', models.URLField(blank=True, max_length=255, null=True)),
                ('display_name', models.BooleanField(default=True)),
                ('display_logs', models.BooleanField(default=True)),
                ('access_token', models.CharField(blank=True, max_length=64, null=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='socialaccount.socialaccount')),
            ],
        ),
    ]
