# Generated by Django 5.1 on 2024-08-30 18:34

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_id', models.IntegerField()),
                ('fight_end', models.IntegerField(db_index=True)),
                ('fight_duration', models.IntegerField(db_index=True)),
                ('local_player', models.CharField(db_index=True, max_length=16)),
                ('boss_name', models.CharField(db_index=True, max_length=64)),
                ('difficulty', models.CharField(db_index=True, max_length=10)),
                ('max_hp', models.BigIntegerField(null=True)),
                ('npc_id', models.IntegerField(null=True)),
                ('player_data', models.JSONField()),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['player_data'], name='database_en_player__53ad79_gin')],
            },
        ),
    ]
